path1 = r'C:\Users\talgx\AndroidStudioProjects\roadgaurd\app\src\main\res\layout\activity_notifications.xml'
path2 = r'C:\Users\talgx\AndroidStudioProjects\roadgaurd\app\src\main\res\layout\item_notification.xml'

xml1 = '<?xml version="1.0" encoding="utf-8"?>\n<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"\n    android:layout_width="match_parent"\n    android:layout_height="match_parent"\n    android:orientation="vertical"\n    android:background="@color/black">\n    <Button\n        android:id="@+id/btnMarkAllRead"\n        android:layout_width="match_parent"\n        android:layout_height="48dp"\n        android:text="Mark All Read"\n        android:layout_margin="8dp"/>\n    <androidx.recyclerview.widget.RecyclerView\n        android:id="@+id/rvNotifications"\n        android:layout_width="match_parent"\n        android:layout_height="0dp"\n        android:layout_weight="1"/>\n</LinearLayout>'

xml2 = '<?xml version="1.0" encoding="utf-8"?>\n<androidx.cardview.widget.CardView\n    xmlns:android="http://schemas.android.com/apk/res/android"\n    xmlns:app="http://schemas.android.com/apk/res-auto"\n    android:id="@+id/cardNotification"\n    android:layout_width="match_parent"\n    android:layout_height="wrap_content"\n    android:layout_margin="8dp"\n    app:cardCornerRadius="12dp"\n    app:cardBackgroundColor="@color/card_dark">\n    <LinearLayout\n        android:layout_width="match_parent"\n        android:layout_height="wrap_content"\n        android:orientation="horizontal"\n        android:padding="16dp"\n        android:gravity="center_vertical">\n        <ImageView\n            android:id="@+id/ivIcon"\n            android:layout_width="40dp"\n            android:layout_height="40dp"\n            android:layout_marginEnd="16dp"/>\n        <LinearLayout\n            android:layout_width="0dp"\n            android:layout_height="wrap_content"\n            android:layout_weight="1"\n            android:orientation="vertical">\n            <TextView\n                android:id="@+id/tvMessage"\n                android:layout_width="wrap_content"\n                android:layout_height="wrap_content"\n                android:textColor="@color/white"\n                android:textSize="15sp"\n                android:textStyle="bold"/>\n            <TextView\n                android:id="@+id/tvTimestamp"\n                android:layout_width="wrap_content"\n                android:layout_height="wrap_content"\n                android:textColor="@color/gray_text"\n                android:textSize="12sp"\n                android:layout_marginTop="4dp"/>\n        </LinearLayout>\n    </LinearLayout>\n</androidx.cardview.widget.CardView>'

open(path1, 'wb').write(xml1.encode('utf-8'))
open(path2, 'wb').write(xml2.encode('utf-8'))
print('Done!', 'notifications:', len(xml1), 'item:', len(xml2))
