# Auto-generated by calibrate_distance.py � do not edit manually.

BEST_MODEL = "power_law"

# distance = A_CP / (pixel_height + B_CP)
A_CP = 2291.3468568345656
B_CP = 4.438922125161157

# distance = A_PL * pixel_height ** B_PL
A_PL = 1541.6977610045572
B_PL = -0.9219913054628024
