"""
r2_client -- Cloudflare R2 object-storage client for Road Guard.

Architecture
------------
Videos and evidence bundles live in R2, NOT on the Node backend server.
The backend generates one-time presigned URLs and hands them to the app
(to upload a clip) and to the brain (as part of the job payload). The
brain downloads the clip, processes it, then uploads the evidence bundle
back to R2 via another presigned PUT URL — all without the backend ever
touching the bytes.

This module wraps boto3 (S3-compatible API) to:
  * generate presigned GET/PUT URLs (backend → app / backend → brain)
  * upload a local file directly to R2 (brain POST-processing)
  * download a file from R2 (convenience; normally done via ingest_client)
  * check + enforce a 3 GB total-bucket cap before any upload
  * list / delete objects (cleanup / admin)

Credentials are read from environment variables (loaded from .env by the
caller, never hardcoded here):

    CF_R2_ACCESS_KEY_ID
    CF_R2_SECRET_ACCESS_KEY
    CF_R2_ENDPOINT       -- https://<account-id>.r2.cloudflarestorage.com
    CF_R2_BUCKET         -- default bucket name
    CF_R2_MAX_BYTES      -- hard cap (default 3 GB = 3221225472 bytes)

Install dependency: pip install boto3
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Optional

# boto3 is lazy-imported so the rest of the pipeline can still run if it is
# not installed (brain-only mode without Cloudflare).
_boto3 = None


def _b3():
    global _boto3
    if _boto3 is None:
        import boto3
        _boto3 = boto3
    return _boto3


# --------------------------------------------------------------------------- #
# Constants / defaults
# --------------------------------------------------------------------------- #
_DEFAULT_MAX_BYTES = 3 * 1024 ** 3   # 3 GB


@dataclass
class R2Config:
    access_key_id: str
    secret_access_key: str
    endpoint: str
    bucket: str
    max_bytes: int = _DEFAULT_MAX_BYTES

    @classmethod
    def from_env(cls) -> "R2Config":
        """Load config from environment variables. Raises if required vars are missing."""
        missing = [v for v in ("CF_R2_ACCESS_KEY_ID", "CF_R2_SECRET_ACCESS_KEY",
                               "CF_R2_ENDPOINT", "CF_R2_BUCKET") if not os.environ.get(v)]
        if missing:
            raise EnvironmentError(
                f"Missing Cloudflare R2 env vars: {missing}. "
                "Copy .env.example -> .env and fill in your credentials.")
        return cls(
            access_key_id=os.environ["CF_R2_ACCESS_KEY_ID"],
            secret_access_key=os.environ["CF_R2_SECRET_ACCESS_KEY"],
            endpoint=os.environ["CF_R2_ENDPOINT"].rstrip("/"),
            bucket=os.environ["CF_R2_BUCKET"],
            max_bytes=int(os.environ.get("CF_R2_MAX_BYTES", _DEFAULT_MAX_BYTES)),
        )


# --------------------------------------------------------------------------- #
# Client
# --------------------------------------------------------------------------- #
class R2Client:
    """Thin boto3 wrapper for Cloudflare R2 (S3-compatible)."""

    def __init__(self, config: R2Config | None = None):
        self._cfg = config or R2Config.from_env()
        self._s3 = _b3().client(
            "s3",
            endpoint_url=self._cfg.endpoint,
            aws_access_key_id=self._cfg.access_key_id,
            aws_secret_access_key=self._cfg.secret_access_key,
            region_name="auto",
        )

    # ------------------------------------------------------------------ #
    # Storage accounting
    # ------------------------------------------------------------------ #
    def bucket_size_bytes(self) -> int:
        """Return the total bytes stored in the bucket (all objects, all pages)."""
        total = 0
        paginator = self._s3.get_paginator("list_objects_v2")
        for page in paginator.paginate(Bucket=self._cfg.bucket):
            for obj in page.get("Contents", []):
                total += obj.get("Size", 0)
        return total

    def check_capacity(self, upload_bytes: int = 0) -> tuple[int, int]:
        """Check whether there is room for `upload_bytes` more data.

        Returns (current_bytes, max_bytes). Raises StorageCapacityError if
        adding `upload_bytes` would exceed the configured cap.
        """
        current = self.bucket_size_bytes()
        if current + upload_bytes > self._cfg.max_bytes:
            raise StorageCapacityError(
                f"R2 bucket would exceed the {self._cfg.max_bytes / 1e9:.1f} GB cap "
                f"(current {current / 1e9:.2f} GB + upload {upload_bytes / 1e6:.1f} MB). "
                "Delete old bundles or raise CF_R2_MAX_BYTES.")
        return current, self._cfg.max_bytes

    # ------------------------------------------------------------------ #
    # Presigned URLs (generated by backend, consumed by app / brain)
    # ------------------------------------------------------------------ #
    def presign_get(self, key: str, expires_in: int = 3600) -> str:
        """Generate a presigned GET URL for `key` (one-time video download for the brain)."""
        return self._s3.generate_presigned_url(
            "get_object",
            Params={"Bucket": self._cfg.bucket, "Key": key},
            ExpiresIn=expires_in,
        )

    def presign_put(self, key: str, expires_in: int = 3600,
                    content_type: str = "application/octet-stream") -> str:
        """Generate a presigned PUT URL for `key` (one-time upload slot for app / brain)."""
        return self._s3.generate_presigned_url(
            "put_object",
            Params={"Bucket": self._cfg.bucket, "Key": key,
                    "ContentType": content_type},
            ExpiresIn=expires_in,
        )

    # ------------------------------------------------------------------ #
    # Direct upload / download (brain side, post-processing)
    # ------------------------------------------------------------------ #
    def upload_file(self, local_path: str, key: str, *,
                    content_type: str = "application/octet-stream",
                    check_cap: bool = True) -> str:
        """Upload `local_path` to R2 under `key`.

        Checks the 3 GB cap before sending unless `check_cap=False`.
        Returns the public-ish object URL (NOT a presigned URL -- use presign_get
        to share it externally; this URL is for internal reference only).
        """
        size = os.path.getsize(local_path)
        if check_cap:
            self.check_capacity(size)
        self._s3.upload_file(
            local_path, self._cfg.bucket, key,
            ExtraArgs={"ContentType": content_type},
        )
        return f"{self._cfg.endpoint}/{self._cfg.bucket}/{key}"

    def upload_bytes(self, data: bytes, key: str, *,
                     content_type: str = "application/octet-stream",
                     check_cap: bool = True) -> str:
        """Upload raw `data` bytes to R2 under `key`. Checks the 3 GB cap."""
        if check_cap:
            self.check_capacity(len(data))
        import io
        self._s3.upload_fileobj(
            io.BytesIO(data), self._cfg.bucket, key,
            ExtraArgs={"ContentType": content_type},
        )
        return f"{self._cfg.endpoint}/{self._cfg.bucket}/{key}"

    def download_file(self, key: str, dest_path: str) -> str:
        """Download R2 object `key` to `dest_path`. Returns dest_path."""
        os.makedirs(os.path.dirname(os.path.abspath(dest_path)) or ".", exist_ok=True)
        self._s3.download_file(self._cfg.bucket, key, dest_path)
        return dest_path

    # ------------------------------------------------------------------ #
    # Listing / deletion (admin / cleanup)
    # ------------------------------------------------------------------ #
    def list_objects(self, prefix: str = "") -> list[dict]:
        """Return all objects under `prefix` as a list of {key, size, last_modified}."""
        result = []
        paginator = self._s3.get_paginator("list_objects_v2")
        for page in paginator.paginate(Bucket=self._cfg.bucket, Prefix=prefix):
            for obj in page.get("Contents", []):
                result.append({
                    "key": obj["Key"],
                    "size": obj["Size"],
                    "last_modified": obj["LastModified"],
                })
        return result

    def delete_object(self, key: str) -> None:
        """Delete a single object from the bucket."""
        self._s3.delete_object(Bucket=self._cfg.bucket, Key=key)

    def delete_objects(self, keys: list[str]) -> int:
        """Batch-delete up to 1000 keys per call. Returns number of keys deleted."""
        if not keys:
            return 0
        deleted = 0
        for i in range(0, len(keys), 1000):
            batch = [{"Key": k} for k in keys[i:i + 1000]]
            resp = self._s3.delete_objects(
                Bucket=self._cfg.bucket, Delete={"Objects": batch})
            deleted += len(resp.get("Deleted", []))
        return deleted

    # ------------------------------------------------------------------ #
    # Job-payload helpers (backend uses these to build the brain's job)
    # ------------------------------------------------------------------ #
    def make_job_payload(self, job_id: str, video_key: str, bundle_key: str,
                         notify_url: str, video_meta: dict | None = None,
                         video_expires: int = 3600, bundle_expires: int = 7200) -> dict:
        """Build the job payload the backend sends to the brain.

        Returns a dict ready to JSON-serialize and POST to the brain worker:
            {
              "job_id":      "...",
              "video_url":   "<presigned GET>",   # brain downloads the clip from here
              "upload_url":  "<presigned PUT>",   # brain uploads the bundle here
              "notify_url":  "...",               # brain POSTs here when done
              "video_meta":  {...},               # reference fingerprint (from DB)
              "object_key":  "...",               # bundle key (for the backend to retrieve later)
            }
        """
        return {
            "job_id":     job_id,
            "video_url":  self.presign_get(video_key, expires_in=video_expires),
            "upload_url": self.presign_put(bundle_key, expires_in=bundle_expires,
                                           content_type="application/x-tar"),
            "notify_url": notify_url,
            "object_key": bundle_key,
            "video_meta": video_meta or {},
        }


# --------------------------------------------------------------------------- #
# Errors
# --------------------------------------------------------------------------- #
class StorageCapacityError(RuntimeError):
    """Raised when an upload would exceed the configured R2 storage cap."""


# --------------------------------------------------------------------------- #
# Convenience: load .env automatically when used as a script
# --------------------------------------------------------------------------- #
def _load_dotenv() -> None:
    env_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env")
    if not os.path.exists(env_path):
        return
    with open(env_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            os.environ.setdefault(k.strip(), v.strip())


if __name__ == "__main__":
    _load_dotenv()
    client = R2Client()
    used, cap = client.check_capacity()
    print(f"R2 bucket usage: {used / 1e9:.3f} GB / {cap / 1e9:.1f} GB")
    objects = client.list_objects()
    print(f"Objects: {len(objects)}")
    for o in objects[:10]:
        print(f"  {o['key']}  ({o['size'] / 1e6:.1f} MB)  {o['last_modified']}")
