"""
Per-vehicle distance estimate from a detection bounding box (meters).

PORTED from Moshe's distance work on branch `moshe-main_file`
  - speed_estimator.py : estimateDistance() -> writes vehicle.dist_per_frame
  - distance_model.py  : calibration constants (auto-generated by calibrate_distance.py)

That code is NOT yet merged into main, so we copy the closed-form model here so the
crossing harness can compute distance from the bounding boxes it already caches — no
dependency on the unmerged branch.

The model is a pure function of bbox PIXEL HEIGHT (y2 - y1): a taller box means the car
is closer. Two calibrated forms exist; Moshe's `BEST_MODEL` is "power_law":

    power_law:         distance = A_PL * pixel_height ** B_PL
    corrected_pinhole: distance = A_CP / (pixel_height + B_CP)

CAVEAT: the calibration is camera-specific (tuned on one 1080p / ~90deg-FOV dashcam).
On assorted YouTube dashcams the ABSOLUTE meters are not trustworthy, but the model is
monotonic in bbox height, so it is fine as a per-vehicle RELIABILITY signal (closer =>
higher confidence). Do not present these as true ground-truth meters.

TODO(post-merge): once `moshe-main_file` lands in main, delete this and call
speed_estimator.estimateDistance(world) so there is a single source of truth.
"""
from __future__ import annotations

# --- calibration constants, copied verbatim from moshe-main_file:distance_model.py ---
BEST_MODEL = "power_law"
A_CP = 2291.3468568345656          # corrected pinhole
B_CP = 4.438922125161157
A_PL = 1541.6977610045572          # power law
B_PL = -0.9219913054628024


def distance_from_pixel_height(pixel_height: float, model: str = BEST_MODEL) -> float:
    """Estimated distance in meters from a bbox's pixel height. 0.0 for a degenerate box."""
    if pixel_height <= 0:
        return 0.0
    if model == "corrected_pinhole":
        return A_CP / (pixel_height + B_CP)
    # default / "power_law"
    return A_PL * (pixel_height ** B_PL)


def distance_from_bbox(bbox, model: str = BEST_MODEL) -> float:
    """bbox = (x1, y1, x2, y2). Distance in meters from its pixel height (y2 - y1)."""
    _, y1, _, y2 = bbox
    return distance_from_pixel_height(y2 - y1, model)


if __name__ == "__main__":
    # sanity check: distance must DECREASE monotonically as the box gets taller (car nearer)
    print(f"model={BEST_MODEL}  A_PL={A_PL:.3f}  B_PL={B_PL:.4f}")
    print(f"{'pixel_height':>12} | {'power_law(m)':>12} | {'pinhole(m)':>11}")
    print("-" * 42)
    prev = None
    for ph in (20, 40, 60, 100, 150, 200, 300, 500):
        d_pl = distance_from_pixel_height(ph, "power_law")
        d_cp = distance_from_pixel_height(ph, "corrected_pinhole")
        mono = "" if prev is None else ("  OK" if d_pl < prev else "  !! non-monotonic")
        print(f"{ph:>12} | {d_pl:>12.2f} | {d_cp:>11.2f}{mono}")
        prev = d_pl
